name: example
description: Showcase Arna.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arna:
    path: ../
  flutter_riverpod: ^2.0.0-dev.5
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
