name: example
description: Showcase Arna.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arna:
    path: ../
  flutter_riverpod: ^2.0.0-dev.6
  url_launcher: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
